import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ScheduleDataProvider } from "../components/ScheduleDataProvider";
import { UrqlProvider } from "../components/UrqlProvider";
import { Header } from "../components/Header";
import dynamic from "next/dynamic";
const Gantt = dynamic(() => import("../components/Gantt"), {
  ssr: false,
});

import { useQuery } from "urql";

const findProjectByID = `
  query FindProjectByID($id: ID!) {
    findProjectByID(id: $id) {
      _id
      name
      tasks {
        data {
          _id
          text
          start_date
          end_date
          duration
          progress
          parent
          open
        }
      }
      links {
        data {
          _id
          source
          target
        }
      }
    }
  }
`;

const Projects = ({ id }: { id: string }) => {
  const [result, reexecuteQuery] = useQuery({
    query: findProjectByID,
    variables: { id },
  });

  const { data, fetching, error } = result;

  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no... {error.message}</p>;

  console.log(data);

  return (
    <>
      {/* {data.allProjects.data.map((d: any) => {
        return d.tasks.data.map((d: any) => <p>{d.text}</p>);
      })} */}
    </>
  );
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UrqlProvider>
        <Projects id="334725058471658066" />
      </UrqlProvider>
      <Header />
      <main className={styles.main}>
        <ScheduleDataProvider>
          <Gantt />
        </ScheduleDataProvider>
      </main>
    </div>
  );
};

export default Home;
