import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ScheduleDataProvider } from "../components/ScheduleDataProvider";
import { UrqlProvider } from "../components/UrqlProvider";
import { Header } from "../components/Header";
import dynamic from "next/dynamic";
const Gantt = dynamic(() => import("../components/Gantt"), {
  ssr: false,
});

import { useQuery } from "urql";

const BooksQuery = `
  query {
    books {
      title
    }
  }
`;

const BooksMutation = `
  mutation {
    registerBook(title: "test", author:"tester") {
      title
      author
    }
  }
`;

const Books = () => {
  const [result, reexecuteQuery] = useQuery({
    query: BooksQuery,
  });

  const { data, fetching, error } = result;

  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no... {error.message}</p>;

  console.log("books", data);

  return (
    <>
      <ul>
        {data.books.map((book: { title: any }) => (
          <li>{book.title}</li>
        ))}
      </ul>
    </>
  );
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UrqlProvider>
        <Books />
      </UrqlProvider>
      {/* <Header />
      <main className={styles.main}>
        <ScheduleDataProvider>
          <Gantt />
        </ScheduleDataProvider>
      </main> */}
    </div>
  );
};

export default Home;
