import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import TableView from "../components/tableVIew";
import Gantt from "../components/Gantt";
import { ScheduleDataProvider } from "../components/scheduleDataProvider";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ScheduleDataProvider>
          <TableView />
          <Gantt />
        </ScheduleDataProvider>
      </main>
    </div>
  );
};

export default Home;
